### ISSUE TITLE
snake_case naming convention support

### ISSUE THREAD

**Issue by T0shik** [TwentyFourMinutes/Venflow#19]
### Is your feature request related to a problem, if so please describe it.

As there is no database creation logic and the ORM is primarily Postgres it would make sense to support native naming convention, this would making building on top of existing databases easier as well.

### Describe the solution you'd like

I've got a working solution here:
https://github.com/T0shik/Venflow/commit/ddb91f766509e007075f8a70f9a247fec5175965

If you want this change I can create a pull request, if you'd like this to be implemented a particular way feel free to tell me I'll change it.

### Additional context (if any)

Nada

**Comment by TwentyFourMinutes** [comment]
First of all, thanks for your issue and a possible implementation! I have already thought about this in the past and I totally agree with you. However, it would make sense IMO to use the existing `INpgsqlNameTranslator` that Npgsql already provides. There are already existing implementations even for snake_case, see [here](https://www.npgsql.org/doc/api/Npgsql.INpgsqlNameTranslator.html). The idea behind the `INpgsqlNameTranslator` is to be only used for properties/columns. Anyhow I don't see any issue, if we would use it for tables as well.

**Comment by TwentyFourMinutes** [comment]
Also you were already quite right about the direction of your implementation, but instead of just injecting the name translator, lets just inject the whole `Database`, as this would be more future proof. This would even allow us to register PostgreSQL enums only on  a database level, but I can do this afterwards.

**Comment by TwentyFourMinutes** [comment]
Additionally I'd register the `INpgsqlNameTranslator` through the `DatabaseConfigurationOptionsBuilder` rather than the `DatabaseOptionsBuilder`. The `DatabaseOptionsBuilder` get called every time on instantiation in order to allow for dynamic configuration of those supplied values. `DatabaseConfigurationOptionsBuilder` on the other hand will only ever be called once, which is enough for the `INpgsqlNameTranslator`.

**Comment by TwentyFourMinutes** [comment]
If you feel like making those changes and creating a PR, I'd more than appreciate it. If you need any help, let me know.

**Comment by T0shik** [comment]
Sounds good, I'll take a look at getting a PR ready, will get in touch if I have any questions )

**Comment by T0shik** [comment]
opened https://github.com/TwentyFourMinutes/Venflow/pull/24

**Comment by TwentyFourMinutes** [comment]
Thanks a lot for your contribution, I'll release a new version in a few days including this feature :)

**Comment by T0shik** [comment]
happy to contribute )
